<?php 
/*
Plugin Name: Forced Login Bloqued
Plugin URI: https://github.com/hhklik/wp-forced-login-bloqued.git
Description: force login bloqued, stop robot\'s  
Version: 0.0.1
Author: Humberto Herrador
Author URI: https://github.com/hhklik
Text Domain: ktwpflb
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}

/**
 * generar cadena aleatoria 
 * @param  [string] $string [segularmente se envia un microtime, dado que este tiene un cambio mas rapido que el time]
 * @return [string]         [valores mezclados aleatoriamente]
 */
function hashPass_ktwpflb($string) {
    $arrFrom = array("=","I","l");
    $arrTo = array("C","A","B"); 
    return str_replace(
        $arrFrom,
        $arrTo,
        str_shuffle(base64_encode(hash("sha256", base_convert($string, 10, 32))))
    );
}

add_action('login_form','my_added_login_field');
function my_added_login_field(){
    //Output your HTML
	/*session is started if you don't write this line can't use $_Session  global variable*/
	//if(!isset($_GET['loggedout'])){
	//}
	$encryption_key = get_option('kt_encryption_key',true);
	$hashPass_ktwpflb = hashPass_ktwpflb(microtime().$_SERVER['REMOTE_ADDR'].$_SERVER['REMOTE_PORT'].$encryption_key);
	$_SESSION["kt_token_login"] = $hashPass_ktwpflb;
?>
    
    <input type="hidden" name="kttl" value="<?php echo $hashPass_ktwpflb;?>">
    <label style="float: left;">No soy robot</label>
   	<img id="info_img" style="width: 24px;padding: 3px;float: right;cursor: pointer;" src="<?php echo plugin_dir_url(__FILE__).'/assets/img/informacion.svg';?>">
    <label style="display: none;float: left;" id="info_guia">Dar KLIK sobre la estrella hasta que gire y cambie de color</label>
    <div id="contenedor_canvas">
        <canvas id="myCanvas_1" width="270" height="100" style="background-color: cyan;;border:1px solid #d3d3d3;border-radius: 9px 9px 9px 9px;-moz-border-radius: 9px 9px 9px 9px;-webkit-border-radius: 9px 9px 9px 9px;border: 0px solid #000000;"></canvas>
    </div>
    <label id="mensaje"style="background-color: cyan;color: black;border-radius: 5px 5px 5px 5px;-moz-border-radius: 5px 5px 5px 5px;-webkit-border-radius: 5px 5px 5px 5px;border: 0px solid #000000;"></label>
    
<?php
}

function custom_admin_css() {
    wp_register_script('jcanvas', plugin_dir_url(__FILE__).'/assets/js/jcanvas.js', array('jquery'),'', true );
    wp_register_script('jcanvas-captcha', plugin_dir_url(__FILE__).'/assets/js/jcanvas-captcha.js', array('jquery'),'', true );
    wp_enqueue_script('jcanvas');
    wp_enqueue_script('jcanvas-captcha');

    
}
add_action( 'login_enqueue_scripts', 'custom_admin_css', 10 );


function kt_login_init() {
   	session_start();
   	if(isset($_POST['kttl'])){

   		/*if(is_null($_SESSION)){
			session_start();
		}*/
		
		if(!($_POST['kttl'] == $_SESSION["kt_token_login"])){
			echo 'Spanish: ve y busca un codigo para niños <a href="wp-login">click para Regresa a login<a/> <br> English: go and look for a children\'s code <a href="wp-login">click Go back login<a/>';
			exit;
		}
		
   	}else{
   		#bloquear opcion de login cuando no viene del formulario de logueo
   		if(isset($_POST['log']) || isset($_POST['pwd'])){
   			echo 'Esta opcion esta inactiva | This option is inactive';
   			exit;
   		}
   	}
}
add_action('login_init', 'kt_login_init');